[package]
name = "napi-rs-sig-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.16.2"
napi-derive = "2.16.2"

[build-dependencies]
napi-build = "2.1.3"
